export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const SET_LOADING = "SET_LOADING";
export const MAKE_ACTIVE_MEMBER = "MAKE_ACTIVE_MEMBER";
export const CLEAR_ACTIVE_MEMBER = "CLEAR_ACTIVE_MEMBER";
