version: 2.1

jobs:
    units:
        docker:
            - image: circleci/node:7
        steps:
            - checkout
            - run: npm install
            - run: npm run test

orbs:
    cypress: cypress-io/cypress@1.1.0
workflows:
    build:
        jobs:
            - units
            - cypress/run:
                start: 'npm start'
